config/routes.rb
# encoding: UTF-8
# frozen_string_literal: true

Dir['app/models/deposits/**/*.rb'].each { |x| require_dependency x.split('/')[2..-1].join('/') }
Dir['app/models/withdraws/**/*.rb'].each { |x| require_dependency x.split('/')[2..-1].join('/') }

class ActionDispatch::Routing::Mapper
  def draw(routes_name)
    instance_eval(File.read(Rails.root.join("config/routes/#{routes_name}.rb")))
  end
end

Peatio::Application.routes.draw do
  root 'main#index'

  get '/signout' => 'sessions#destroy', :as => :signout
  get '/auth/failure' => 'sessions#failure', :as => :failure
  match '/auth/:provider/callback' => 'sessions#create', via: %i[get post]

  scope module: :private do
    resources :withdraw_destinations, only: %i[ create update ]

    resources :funds, only: [:index] do
      collection do
        post :gen_address
      end
    end

    resources 'deposits/:currency', controller: 'deposits', as: 'deposit', only: %i[ destroy ] do
      collection { post 'gen_address' }
    end

    resources 'withdraws/:currency', controller: 'withdraws', as: 'withdraw', only: %i[ create destroy ]

    get '/history/orders' => 'history#orders', as: :order_history
    get '/history/trades' => 'history#trades', as: :trade_history
    get '/history/account' => 'history#account', as: :account_history

    resources :markets, only: [:show], constraints: MarketConstraint do
      resources :orders, only: %i[ index destroy ] do
        collection do
          post :clear
        end
      end
      resources :order_bids, only: [:create] do
        collection do
          post :clear
        end
      end
      resources :order_asks, only: [:create] do
        collection do
          post :clear
        end
      end
    end
  end

  get 'health/alive', to: 'public/health#alive'
  get 'health/ready', to: 'public/health#ready'

  get 'trading/:market_id', to: BlackHoleRouter.new, as: :trading

  draw :admin

  get '/swagger', to: 'swagger#index'

  mount API::Mount => API::Mount::PREFIX
end

app/views/shared/_flash.html.erb
<div class="flash-message">
  <% if flash[:notice] %>
    <div class="alert alert-dismissable alert-custom-success alert-success">
      <button class="close" type="button" data-dismiss="alert" aria-hidden="true">&times;</button>
      <i class="icon fa fa-check"></i>
      <h2 class="h5 mb-0">
        <span><%= flash[:notice] %></span>
      </h2>
    </div>
  <% end %>

  <% if flash[:alert] %>
    <div class="alert alert-dismissable alert-custom-danger alert-danger">
      <button class="close" type="button" data-dismiss="alert" aria-hidden="true">&times;</button>
      <i class="icon fa fa-times"></i>
      <h2 class="h5 mb-0">
        <span><%= flash[:alert] %></span>
      </h2>
    </div>
  <% end %>

  <% if flash[:info] %>
    <div class="alert alert-dismissable alert-custom-info alert-info">
      <button class="close" type="button" data-dismiss="alert" aria-hidden="true">&times;</button>
      <i class="icon fa fa-info"></i>
      <h2 class="h5 mb-0">
        <span><%= flash[:info] %></span>
      </h2>
    </div>
  <% end %>
</div>

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="container">
    <div class="text-center">
      <span>Version: v<%= Peatio::Application::VERSION %></span>
      <span> | Build date: <%= Peatio::Application::BUILD_DATE %></span>
      <span> | Commit: <%= Peatio::Application::GIT_SHA %></span>
    </div>
  </div>
</footer>

app/views/shared/_frame.html.erb
<div class="container">
  <% if content_for?(:before) %>
    <%= yield(:before) %>
  <% end %>
  <div class="card card-default">
    <div class="card-header">
      <h2 class="card-title"><%= guide_panel_title %></h2>
    </div>
    <div class="card-body">
      <div class="row">
        <div id="guide" class="col-4">
          <% if content_for?(:guide_title) %>
            <%= yield(:guide_title) %>
          <% else %>
            <h3><%= guide_title %></h3>
          <% end %>
          <p class="text-ignore"><%= guide_intro %></p>
          <% if content_for?(:guide) %>
            <%= yield(:guide) %>
          <% end %>
        </div>
        <div id="content" class="col-8">
          <%= render 'shared/flash' %>
          <%= yield %>
        </div>
      </div>
      <% if content_for?(:secondary) %>
        <%= yield(:secondary) %>
      <% end %>
    </div>
  </div>
  <% if content_for?(:after) %>
    <%= yield(:after) %>
  <% end %>
</div>

app/views/shared/_header.html.erb
<header class="mb-4">
  <nav class="navbar navbar-expand-md navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="text-center navbar-brand" href="<%= root_path %>">
        <img class="nav-img" src="<%= ENV['LOGO_URL'] || image_path('logo.svg') %>">
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#top-navbar" aria-controls="top-navbar" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
      <div class="collapse navbar-collapse" id="top-navbar">
        <ul id="menu" class="navbar-nav mr-auto">
          <%= top_nav_link(t('header.market'), trading_path(current_market.id), 'exchange-alt', target: '_blank') if current_user %>
          <%= top_nav_link(t('header.funds'), funds_path, 'money-bill-wave', controllers: ['funds']) if current_user %>
          <%= top_nav_link(t('header.history'), order_history_path, 'book', controllers: ['history']) if current_user %>
        </ul>
        <ul class="navbar-nav ml-auto">
          <%= render partial: 'shared/header_profile_setting' if current_user %>
          <%= render partial: 'shared/header_lang_sel' %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/shared/_header_lang_sel.html.erb
<li class="nav-item dropdown">
  <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown">
    <img src="/languages/<%= I18n.locale %>.png"/>
    <b class="caret"></b>
  </a>
  <div id="languages" class="dropdown-menu">
    <% I18n.available_locales.each do |lang| %>
      <a class="dropdown-item" href="?lang=<%= lang %>">
        <img src="/languages/<%= lang || I18n.locale %>.png"/>
      </a>
    <% end %>
  </div>
</li>

app/views/shared/_header_profile_setting.html.erb
<% controllers = ['settings', 'dashboard'] %>
<% dropdown_class = (controllers & controller_path.split('/')).empty? ? '' : 'active' %>
<li class="nav-item dropdown account-settings text-left <%= dropdown_class %>">
  <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown">
    <span><%= current_user.email %></span>
    <b class="caret"></b>
  </a>
  <div class="dropdown-menu">
    <% if is_admin? %>
      <a class="dropdown-item" href="<%= admin_dashboard_path %>">
        <i class="fa fa-tachometer-alt"></i>
        <span><%= t('header.admin') %></span>
      </a>
    <% end %>
    <a class="dropdown-item" href="<%= main_app.signout_path %>">
      <i class="fa fa-sign-out-alt"></i>
      <span><%= t('header.signout') %></span>
    </a>
  </div>
</li>

app/views/shared/_meta.html.erb
<title><%= ENV.fetch('METADATA_TITLE') %></title>
<meta name="description" content="<%= ENV.fetch('METADATA_DESCRIPTION') %>">
<meta name="keywords" content="<%= ENV.fetch('METADATA_KEYWORDS') %>">

app/views/shared/_sentry.html.erb
<% if defined?(Raven) && ENV['SENTRY_DSN_FRONTEND'].present? %>
    <meta name="sentry-dsn" content="<%= ENV['SENTRY_DSN_FRONTEND'] %>">
<% end %>